### ISSUE TITLE
UserDefaults Bug

### ISSUE THREAD

**Issue by kojake** [kojake/TodoList#1]
# 起きていること
UserDefaults保存できん

# 原因
知るかぼけ
俺が聞きたいわ
原因なってわかってたらもう解決してるわ

**Comment by yuuki00682200** [comment]
#2 #3 #4

**Comment by yuuki00682200** [comment]
@kojake 
直りましたか？

**Comment by kojake** [comment]
治りました!
ちゃんと保存されています
ありがとうございます。

**Comment by yuuki00682200** [comment]
あ、deleteの部分に処理仕込むの忘れていました。Addと同じやり方で仕込めるので自分でやってみてください

**Comment by kojake** [comment]
okです。
